FROM python:3.6

RUN mkdir /code

WORKDIR /code

ADD ./requirements/base.txt /code/requirements/base.txt

ADD ./requirements/local.txt /code/requirements/local.txt

RUN pip install -r /code/requirements/local.txt

ADD . /code	